/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 23
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 1
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_blank_line = 1,
  anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT = 2,
  anon_sym_LF = 3,
  anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT = 4,
  anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT = 5,
  sym_content_line = 6,
  sym_cell_end = 7,
  sym_notebook = 8,
  sym_cell = 9,
  sym_code_cell = 10,
  sym_markdown_cell = 11,
  sym_raw_cell = 12,
  aux_sym_notebook_repeat1 = 13,
  aux_sym_code_cell_repeat1 = 14,
  alias_sym_cell_content = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_blank_line] = "blank_line",
  [anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT] = "# <<ipynb_nvim:code>>",
  [anon_sym_LF] = "\n",
  [anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT] = "# <<ipynb_nvim:markdown>>",
  [anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT] = "# <<ipynb_nvim:raw>>",
  [sym_content_line] = "content_line",
  [sym_cell_end] = "cell_end",
  [sym_notebook] = "notebook",
  [sym_cell] = "cell",
  [sym_code_cell] = "code_cell",
  [sym_markdown_cell] = "markdown_cell",
  [sym_raw_cell] = "raw_cell",
  [aux_sym_notebook_repeat1] = "notebook_repeat1",
  [aux_sym_code_cell_repeat1] = "code_cell_repeat1",
  [alias_sym_cell_content] = "cell_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_blank_line] = sym_blank_line,
  [anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT] = anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT] = anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT,
  [anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT] = anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT,
  [sym_content_line] = sym_content_line,
  [sym_cell_end] = sym_cell_end,
  [sym_notebook] = sym_notebook,
  [sym_cell] = sym_cell,
  [sym_code_cell] = sym_code_cell,
  [sym_markdown_cell] = sym_markdown_cell,
  [sym_raw_cell] = sym_raw_cell,
  [aux_sym_notebook_repeat1] = aux_sym_notebook_repeat1,
  [aux_sym_code_cell_repeat1] = aux_sym_code_cell_repeat1,
  [alias_sym_cell_content] = alias_sym_cell_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_content_line] = {
    .visible = true,
    .named = true,
  },
  [sym_cell_end] = {
    .visible = true,
    .named = true,
  },
  [sym_notebook] = {
    .visible = true,
    .named = true,
  },
  [sym_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_code_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_cell] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_notebook_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_cell_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_cell_content] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [2] = alias_sym_cell_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym_code_cell_repeat1, 2,
    aux_sym_code_cell_repeat1,
    alias_sym_cell_content,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(36);
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == '#') ADVANCE(2);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(39);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == '<') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == '<') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(38);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(40);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(6);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(7);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == '_') ADVANCE(25);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 15:
      if (lookahead == 'b') ADVANCE(12);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(27);
      if (lookahead == 'm') ADVANCE(13);
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == 'k') ADVANCE(18);
      END_STATE();
    case 23:
      if (lookahead == 'm') ADVANCE(3);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 29:
      if (lookahead == 'p') ADVANCE(34);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 31:
      if (lookahead == 'v') ADVANCE(21);
      END_STATE();
    case 32:
      if (lookahead == 'w') ADVANCE(9);
      END_STATE();
    case 33:
      if (lookahead == 'w') ADVANCE(26);
      END_STATE();
    case 34:
      if (lookahead == 'y') ADVANCE(24);
      END_STATE();
    case 35:
      if (eof) ADVANCE(36);
      if (lookahead == '\n') ADVANCE(37);
      if (lookahead == '#') ADVANCE(2);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_blank_line);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 35},
  [2] = {.lex_state = 35},
  [3] = {.lex_state = 35},
  [4] = {.lex_state = 35},
  [5] = {.lex_state = 35},
  [6] = {.lex_state = 35},
  [7] = {.lex_state = 35},
  [8] = {.lex_state = 35},
  [9] = {.lex_state = 35},
  [10] = {.lex_state = 35},
  [11] = {.lex_state = 0, .external_lex_state = 1},
  [12] = {.lex_state = 0, .external_lex_state = 1},
  [13] = {.lex_state = 0, .external_lex_state = 1},
  [14] = {.lex_state = 0, .external_lex_state = 1},
  [15] = {.lex_state = 0, .external_lex_state = 1},
  [16] = {.lex_state = 0, .external_lex_state = 1},
  [17] = {.lex_state = 0, .external_lex_state = 1},
  [18] = {.lex_state = 0, .external_lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_blank_line] = ACTIONS(1),
    [anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT] = ACTIONS(1),
    [anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT] = ACTIONS(1),
    [sym_content_line] = ACTIONS(1),
    [sym_cell_end] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_notebook] = STATE(20),
    [sym_cell] = STATE(2),
    [sym_code_cell] = STATE(4),
    [sym_markdown_cell] = STATE(4),
    [sym_raw_cell] = STATE(4),
    [aux_sym_notebook_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_blank_line] = ACTIONS(5),
    [anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT] = ACTIONS(7),
    [anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT] = ACTIONS(9),
    [anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_cell] = STATE(3),
    [sym_code_cell] = STATE(4),
    [sym_markdown_cell] = STATE(4),
    [sym_raw_cell] = STATE(4),
    [aux_sym_notebook_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_blank_line] = ACTIONS(15),
    [anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT] = ACTIONS(7),
    [anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT] = ACTIONS(9),
    [anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_cell] = STATE(3),
    [sym_code_cell] = STATE(4),
    [sym_markdown_cell] = STATE(4),
    [sym_raw_cell] = STATE(4),
    [aux_sym_notebook_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_blank_line] = ACTIONS(19),
    [anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT] = ACTIONS(22),
    [anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT] = ACTIONS(25),
    [anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT] = ACTIONS(28),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(31), 5,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT,
      anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT,
      anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT,
  [8] = 1,
    ACTIONS(33), 5,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT,
      anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT,
      anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT,
  [16] = 1,
    ACTIONS(35), 5,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT,
      anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT,
      anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT,
  [24] = 1,
    ACTIONS(37), 5,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT,
      anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT,
      anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT,
  [32] = 1,
    ACTIONS(39), 5,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT,
      anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT,
      anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT,
  [40] = 1,
    ACTIONS(41), 5,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT,
      anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT,
      anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT,
  [48] = 1,
    ACTIONS(43), 5,
      ts_builtin_sym_end,
      sym_blank_line,
      anon_sym_POUND_LT_LTipynb_nvim_COLONcode_GT_GT,
      anon_sym_POUND_LT_LTipynb_nvim_COLONmarkdown_GT_GT,
      anon_sym_POUND_LT_LTipynb_nvim_COLONraw_GT_GT,
  [56] = 3,
    ACTIONS(45), 1,
      sym_content_line,
    ACTIONS(47), 1,
      sym_cell_end,
    STATE(16), 1,
      aux_sym_code_cell_repeat1,
  [66] = 3,
    ACTIONS(45), 1,
      sym_content_line,
    ACTIONS(49), 1,
      sym_cell_end,
    STATE(15), 1,
      aux_sym_code_cell_repeat1,
  [76] = 3,
    ACTIONS(45), 1,
      sym_content_line,
    ACTIONS(51), 1,
      sym_cell_end,
    STATE(14), 1,
      aux_sym_code_cell_repeat1,
  [86] = 3,
    ACTIONS(45), 1,
      sym_content_line,
    ACTIONS(53), 1,
      sym_cell_end,
    STATE(17), 1,
      aux_sym_code_cell_repeat1,
  [96] = 3,
    ACTIONS(45), 1,
      sym_content_line,
    ACTIONS(55), 1,
      sym_cell_end,
    STATE(17), 1,
      aux_sym_code_cell_repeat1,
  [106] = 3,
    ACTIONS(45), 1,
      sym_content_line,
    ACTIONS(57), 1,
      sym_cell_end,
    STATE(17), 1,
      aux_sym_code_cell_repeat1,
  [116] = 3,
    ACTIONS(59), 1,
      sym_content_line,
    ACTIONS(62), 1,
      sym_cell_end,
    STATE(17), 1,
      aux_sym_code_cell_repeat1,
  [126] = 1,
    ACTIONS(64), 2,
      sym_content_line,
      sym_cell_end,
  [131] = 1,
    ACTIONS(66), 1,
      anon_sym_LF,
  [135] = 1,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
  [139] = 1,
    ACTIONS(70), 1,
      anon_sym_LF,
  [143] = 1,
    ACTIONS(72), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 8,
  [SMALL_STATE(6)] = 16,
  [SMALL_STATE(7)] = 24,
  [SMALL_STATE(8)] = 32,
  [SMALL_STATE(9)] = 40,
  [SMALL_STATE(10)] = 48,
  [SMALL_STATE(11)] = 56,
  [SMALL_STATE(12)] = 66,
  [SMALL_STATE(13)] = 76,
  [SMALL_STATE(14)] = 86,
  [SMALL_STATE(15)] = 96,
  [SMALL_STATE(16)] = 106,
  [SMALL_STATE(17)] = 116,
  [SMALL_STATE(18)] = 126,
  [SMALL_STATE(19)] = 131,
  [SMALL_STATE(20)] = 135,
  [SMALL_STATE(21)] = 139,
  [SMALL_STATE(22)] = 143,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_notebook, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_notebook, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_notebook_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_notebook_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_notebook_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_notebook_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_notebook_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cell, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_cell, 4, 0, 1),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_cell, 3, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_cell, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_cell, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_cell, 4, 0, 1),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_cell, 4, 0, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_cell_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_cell_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_cell_repeat1, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [68] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_content_line = 0,
  ts_external_token_cell_end = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_content_line] = sym_content_line,
  [ts_external_token_cell_end] = sym_cell_end,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_content_line] = true,
    [ts_external_token_cell_end] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_ipynb_external_scanner_create(void);
void tree_sitter_ipynb_external_scanner_destroy(void *);
bool tree_sitter_ipynb_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_ipynb_external_scanner_serialize(void *, char *);
void tree_sitter_ipynb_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ipynb(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_ipynb_external_scanner_create,
      tree_sitter_ipynb_external_scanner_destroy,
      tree_sitter_ipynb_external_scanner_scan,
      tree_sitter_ipynb_external_scanner_serialize,
      tree_sitter_ipynb_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "ipynb",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
